name: GifTools macOS Xcode

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        token: ${{ secrets.MINIMAL_PAT }}
        path: dependencies/emsdk
        ref: master

    - name: Web amalgamated build
      run: |
        sh giftools-build-for-xcode.sh

    - name: Node tests
      run: |
        sh giftools-run-xcode-tests.sh
