name: GifTools macOS Xcode

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        token: ${{ secrets.MINIMAL_PAT }}
        path: dependencies/emsdk
        ref: master

    - name: Xcode build
      run: |
        git config --global url."https://github.com/".insteadOf git@github.com:
        git config --global url."https://".insteadOf git://
        git lfs install
        git lfs pull
        sh giftools-build-with-xcode.sh

    - name: Xcode tests
      run: |
        sh giftools-run-xcode-tests.sh
