name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        token: ${{ secrets.MINIMAL_PAT }}
        path: dependencies/emsdk
        ref: master

    - name: Emscripten build for node
      run: |
        sh emsdk-reinstall.sh
        sh giftools-build-with-local-emsdk.sh

    - name: Emscripten build for Web ES6
      run: |
        sh emsdk-reinstall.sh
        sh giftools-build-for-web-es6-with-local-emsdk.sh

    - name: Emscripten build for Web amalgamated
      run: |
        sh emsdk-reinstall.sh
        sh giftools-build-for-web-single-file-with-local-emsdk.sh

    - name: Emscripten build for Web ES6 amalgamated
      run: |
        sh emsdk-reinstall.sh
        sh giftools-build-for-web-es6-single-file-with-local-emsdk.sh
